site_name: Calculation docs

theme:
  name: "material"

nav:
  - Homepage: index.md
  - Tutorials: tutorials.md
  - Guidelines: how-to-guides.md
  - Where are you from: reference.md
  - How it works: explanation.md